#!/usr/bin/env node
// Writes package.json's version into src/version.ts (used for the User-Agent header).
// Runs automatically on `npm version`; a unit test fails if the two ever drift apart.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src", "version.ts");
const content = `// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand:
// run \`npm run sync:version\` (it also runs automatically on \`npm version\`).
/** The version of this SDK (\`@ninjavault/cdn\`), sent in the \`User-Agent\` header. */
export const SDK_VERSION = "${version}";
`;
if (readFileSync(target, "utf8") === content) {
  console.log(`src/version.ts already at ${version}`);
} else {
  writeFileSync(target, content);
  console.log(`src/version.ts updated to ${version}`);
}
