// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand:
// run `npm run sync:version` (it also runs automatically on `npm version`).
/** The version of this SDK (`@ninjavault/cdn`), sent in the `User-Agent` header. */
export const SDK_VERSION = "100.42.1";
